DOMAIN = "energy_management"
VERSION = "v11.6.112"

CONF_CONSUMPTION_SENSORS = "consumption_sensors"
CONF_GENERATION_SENSORS = "generation_sensors"
CONF_GRID_SENSORS = "grid_sensors"
CONF_BATTERY_SENSORS = "battery_sensors"
CONF_PRICE_SENSOR = "price_sensor"
CONF_SOLCAST_SENSOR = "solcast_sensor"

CONF_MIN_SOC = "min_soc"
CONF_BATTERY_CAPACITY = "battery_capacity"
CONF_BATTERY_MAX_POWER = "battery_max_power"
CONF_PRICE_SELL_LIMIT = "price_sell_limit"
CONF_PRICE_BUY_LIMIT = "price_buy_limit"
CONF_ARBITRAGE_ENABLED = "arbitrage_enabled"
CONF_SURVIVAL_ENABLED = "survival_enabled"
CONF_AUTO_SELL_ENABLED = "auto_sell_enabled"
CONF_DYNAMIC_SOC_SELL = "dynamic_soc_sell"
CONF_ARBITRAGE_PROFIT_THRESHOLD = "arbitrage_profit_threshold"
CONF_DEGRADATION_COST = "degradation_cost"
CONF_SOC_BUFFER = "soc_buffer"
CONF_NIGHT_DRAIN_LIMIT = "night_drain_limit"
CONF_SUNRISE_OFFSET = "sunrise_offset"
CONF_SUNSET_OFFSET = "sunset_offset"
